# Generated by Django 3.0.5 on 2020-04-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
